In [1]:
import numpy as np

## 1. Creating numpy array

In [9]:
myarr = np.array([[3, 6, 32, 7]], np.int64)
myarr

array([[ 3,  6, 32,  7]])

## 2. Accessing numpy array

In [10]:
myarr[0,1]

np.int64(6)

## 3. Get shape of array

In [12]:
myarr.shape

(1, 4)

## 4. Changing elements

In [14]:
myarr[0,1] = 45
myarr[0,1]

np.int64(45)

## 5. Array creation: From python structures

In [15]:
# Array creation: conversion from other python structures
listarray = np.array([[1, 2, 3], [5, 8, 5], [0, 3, 1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
print(listarray.shape)
print(listarray.size)

(3, 3)
9


In [17]:
np.array({22, 45, 56})

array({56, 45, 22}, dtype=object)

## 6. Array creation: From array creation methods

In [20]:
# zeros array of a given shape
zeroes = np.zeros((2,5))
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeroes.shape

(2, 5)

In [23]:
zeroes.dtype

dtype('float64')

In [25]:
# array of sequential numbers till the given range
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# array of N random numbers from a given range
lspace = np.linspace(1, 50, 10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
# array of empty elements of a given shape
emp = np.empty((4,6))
emp

array([[8.65203688e-312, 8.65203688e-312, 8.65203688e-312,
        8.65203688e-312, 8.65203688e-312, 8.65203688e-312],
       [8.65203688e-312, 8.65203688e-312, 8.65203688e-312,
        8.65203688e-312, 8.65205965e-312, 8.65203688e-312],
       [8.65203688e-312, 8.65203688e-312, 8.65203687e-312,
        8.65205963e-312, 8.65203688e-312, 8.65203688e-312],
       [8.65203688e-312, 8.65203688e-312, 8.65203688e-312,
        8.65205964e-312, 8.65203687e-312, 8.65203688e-312]])

In [28]:
# creates an empty array of size similar to existing array
emp_like = np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
# identity matrix of size N
ide = np.identity(45)
ide

## 7. Reshaping an array

In [37]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr.shape

(99,)

In [39]:
arr = arr.reshape(3, 33)
arr.shape

(3, 33)

## 8. Transforming an array to 1D array

In [40]:
arr = arr.ravel()

In [42]:
arr.shape

(99,)

## 9. Finding sum of elements

In [51]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [52]:
arr = np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
arr.sum(axis = 0) # rowwise
arr.sum(axis = 1) # columnwise

array([ 6, 15,  8])

## 10. Transpose of array

In [54]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

# 11. iterate over an array

In [55]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


## 12. Get dimensions of an array

In [56]:
arr.ndim

2

## 13. Get the number of elements in array

In [57]:
arr.size

9

## 14. Get the total bytes consumed by an array

In [58]:
arr.nbytes

72

## 15. Get the index of largest element

In [59]:
one =  np.array([1, 3, 4, 634, 2])

In [60]:
one.argmax()

np.int64(3)

## 15. Get the index of smallest element

In [62]:
one.argmin()

np.int64(0)

## 16. Get the indexes of elements which will sort the array

In [61]:
one.argsort()

array([0, 4, 1, 2, 3])

## 17. Mathematical operators

In [71]:
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [72]:
ar2 = np.array([[1, 2, 1], [4, 0, 6], [8, 1, 0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [73]:
# adding two arrays
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [74]:
# multiplying two arrays
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
# find element-wise square root
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [76]:
# find the sum of all elements
ar.sum()

np.int64(29)

In [77]:
# get the largest element in array
ar.max()

np.int64(7)

In [78]:
# get the smallest element in array
ar.min()

np.int64(0)

In [80]:
# get the total number of non-zero elements in arrya
np.count_nonzero(ar)

8

## 18. Filtering elements 

In [79]:
# find indexes of elements that satisfy the condition
np.where(ar > 5)

(array([1, 2]), array([2, 0]))

## 20. Proving numpy is storage effiecent

In [82]:
import sys

In [90]:
py_ar = [0, 4, 55, 2]

In [91]:
np_arr = np.array(py_ar)

In [92]:
sys.getsizeof(1) * len(py_ar)

112

In [93]:
np_arr.itemsize * np_arr.size

32