## Installation

In [ ]:
#pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: C:\Users\pranj\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


## Importing

In [2]:
import numpy as np

## Creating Numpy arrays

In [ ]:
# creating 1D array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
# creating 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
# get dimensions of array
print(a.ndim)
print(b.ndim)

1
2


In [8]:
# get shape of array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# get the type of array
print(a.dtype)
print(b.dtype)

int64
float64
<class 'numpy.ndarray'>


In [ ]:
# get the total number of elements 
print(a.size)
print(b.size)

3
6


## Accessing specific elements

In [23]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [24]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# get specific elements ->  array[row_index, column_index]
a[1, 5]

np.int64(13)

In [ ]:
# get a specific row ->  array [row_index, :]
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# get a specific column ->  array [:, column_index]
a[: , 2]

array([ 3, 10])

In [18]:
# slicing
a[0, 1:6:2]

array([2, 4, 6])

## Modifying elements 

In [19]:
# modifying elements at a speicific index ->  array [row_index, column_index]
a[1, 5] = 20

In [20]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [ ]:
# modifying all the elements at a specific column ->  array [: , column_index]
a[:, 2] = 5

In [26]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 13, 14]])

In [29]:
# modifying all the elements at a specific row ->  array [row_index, :]
a[1, :] = 10

In [30]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [10, 10, 10, 10, 10, 10, 10]])

## Initializing different types of arrays

In [ ]:
## all zeroes matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# all ones matrix
np.ones((4, 2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [36]:
# all full number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [38]:
# any other number (full-like)
np.full_like(a.shape, 4)

array([4, 4])

In [40]:
# random decimal numbers
np.random.rand(4, 2)

array([[0.51167272, 0.40590109],
       [0.8828736 , 0.68721395],
       [0.91550069, 0.45507478],
       [0.76277892, 0.625657  ]])

In [43]:
# random integer numbers
np.random.randint(2, 7, size=(3,3))

array([[4, 4, 6],
       [4, 4, 4],
       [2, 3, 6]], dtype=int32)

In [44]:
# create an identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Copying arrays

In [ ]:
# copying array, pass by reference
a = np.array([[1, 2, 3]])
b = a
b[0] = 100

In [46]:
print(b)
print(a)

[[100 100 100]]
[[100 100 100]]


In [ ]:
# copying array, pass by value
a = np.array([[1, 2, 3]])
b = a.copy()
b[0] = 100

In [48]:
print(b)
print(a)

[[100 100 100]]
[[1 2 3]]


## Mathematical Operations

In [49]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [ ]:
# elementwise addition
a = a + 2
print(a)

[1 2 3 4]


In [52]:
# elementwise subtraction
a = a - 2
print(a)

[-1  0  1  2]


In [53]:
# elementwise multiplication
a = a * 2
print(a)

[-2  0  2  4]


In [54]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [55]:
b = np.array([1, 0, 1, 0])
b

array([1, 0, 1, 0])

In [56]:
# elementwise adddition
print(a + b)

[2 2 4 4]


In [58]:
# elementwise subtraction
print(a - b)

[0 2 2 4]


In [ ]:
# get the sine of each element in array
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [60]:
# get the cosine of each element in array
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear algebra

In [62]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [65]:
# perform a matrix multiplication
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics

In [67]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
# get mean 
stats.mean()

np.float64(3.5)

In [71]:
# get the minimum value in array
np.min(stats)

np.int64(1)

In [72]:
# get the maximum value in array
np.max(stats)

np.int64(6)

In [ ]:
# get the maximum value in array, column wise
np.max(stats, axis=1)

array([3, 6])

## Reorganizing arrays

In [74]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before.shape)

(2, 4)


In [75]:
# reshape the array
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [77]:
# vertically stacking 
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [78]:
# Horizontally stacking 
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

print(np.hstack([v1, v2]))

[1 2 3 4 5 6 7 8]


## Filtering

In [79]:
a = np.array([[100, 200, 300, 500], [10, 20, 30, 40]])
a

array([[100, 200, 300, 500],
       [ 10,  20,  30,  40]])

In [81]:
a > 50

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [ ]:
# get list of elements greater than 50 from numpy array
a[a > 50]

array([100, 200, 300, 500])